### PR TITLE
Closes #149. Fix type error when creating response with headers param…

### LINKED ISSUE #149: TypeError: Argument 2 passed to yii\httpclient\Client::createResponse() must be of the type array, null given
This issue has originally been reported by @sizeg at https://github.com/yiisoft/yii2/issues/16241.
Moved here by @samdark.

-----

### What steps will reproduce the problem?

If stream_get_contents() inside yii\httpclient\StreamTransport::send() method return false, then $http_response_header will be null.
```php
        try {
            $context = stream_context_create($contextOptions);
            $stream = fopen($url, 'rb', false, $context);
            $responseContent = stream_get_contents($stream);
            // see http://php.net/manual/en/reserved.variables.httpresponseheader.php
            $responseHeaders = $http_response_header;
            fclose($stream);
        } catch (\Exception $e) {
            Yii::endProfile($token, __METHOD__);
            throw new Exception($e->getMessage(), $e->getCode(), $e);
        }

        Yii::endProfile($token, __METHOD__);

        // Here $responseContent false and $responseHeaders is null
        $response = $request->client->createResponse($responseContent, $responseHeaders);
```

### What is the expected result?

According to [php doc example](http://php.net/manual/en/reserved.variables.httpresponseheader.php#refsect1-reserved.variables.httpresponseheader-examples) `$http_response_header` may be `null`. So I think we should convert it to array before calling `$request->client->createResponse()`.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14-dev
| PHP version      | 7.1.6
| Operating system | CentOS Linux 7

Log trace
```
2018-04-18 05:49:35 [::1][-][-][error][TypeError] TypeError: Argument 2 passed to yii\httpclient\Client::createResponse() must be of the type array, null given, called in /var/www/project/vendor/yiisoft/yii2-httpclient/StreamTransport.php on line 73 and defined in /var/www/project/vendor/yiisoft/yii2-httpclient/Client.php:200
Stack trace:
#0 /var/www/project/vendor/yiisoft/yii2-httpclient/StreamTransport.php(73): yii\httpclient\Client->createResponse(false, NULL)
#1 /var/www/project/vendor/yiisoft/yii2-httpclient/Client.php(221): yii\httpclient\StreamTransport->send(Object(yii\httpclient\Request))
#2 /var/www/project/vendor/yiisoft/yii2-httpclient/Request.php(421): yii\httpclient\Client->send(Object(yii\httpclient\Request))
```

### PR DESCRIPTION
**Pull request by alexkart**
Fix type error when creating a response with headers param equals to null.

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #149

### CODE REVIEW

File: tests/ClientTest.php [hunk 1]
```diff
@@ -200,8 +200,8 @@ public function testCreateResponseWithHeadersEqualToNull()
         $client = new Client();
         $response = $client->createResponse('content', null);
         $headersCollection = $response->getHeaders();
-        $this->assertInstanceOf( Response::class, $response);
-        $this->assertInstanceOf(HeaderCollection::class, $headersCollection);
+        $this->assertTrue($response instanceof Response);
+        $this->assertTrue($headersCollection instanceof HeaderCollection);
```
Comment (machour) [inline tests/ClientTest.php]: Shouldn't you use ::className() instead an keep assertInstanceOf() ?

File: src/Client.php [hunk 2]
```diff
@@ -202,8 +202,9 @@ public function createRequest()
      * @return Response request instance.
      * @throws \yii\base\InvalidConfigException
      */
-    public function createResponse($content = null, array $headers = [])
+    public function createResponse($content = null, $headers = null)
```
Comment (rob006) [inline src/Client.php]: This is not BC, since it changes method signature. What if we use:

```suggestion
    public function createResponse($content = null, array $headers = null)
```

Comment (alexkart) [reply src/Client.php]: @rob006, I think it's completely backward compatible. Could you think of any case that can break after this change?

Comment (rob006) [reply src/Client.php]: If I'm already extending this method with old signature, I will get warning after this change: https://3v4l.org/3fTW0

Also removing `array` typehint is just less safe, so I'm not sure what we're win by this.

Comment (alexkart) [reply src/Client.php]: Using `array $headers = null` will also trigger warning in this case.
We can move a casting to an array to StreamTransport before passing header to createResponse, but this issue can occur in other transports as well.
So, any ideas which case is better?

Comment (samdark) [reply src/Client.php]: Yes. Changing signature isn't what we can merge into 2.x.

Comment (samdark) [reply src/Client.php]: @rob006 original change: https://3v4l.org/gsuIm

Comment (alexkart) [reply src/Client.php]: Made changes.

Comment (samdark) [reply src/Client.php]: @rob006 your proposal triggers a warning as well: https://3v4l.org/YhqPu

**Comment by samdark** [comment]
Merged. Thank you!
